// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdpcnRzUwlJYnvMqGtiZ0s5o2ORAmi5A4',
    appId: '1:738291461408:web:8ae25c6659b03b86c87b45',
    messagingSenderId: '738291461408',
    projectId: 'pollex-18b14',
    authDomain: 'pollex-18b14.firebaseapp.com',
    storageBucket: 'pollex-18b14.appspot.com',
    measurementId: 'G-7YDN7NWEHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3c2QUQxbd7slAEUpc8yZZOqmrG6bCdic',
    appId: '1:738291461408:android:c26d541ea53c3648c87b45',
    messagingSenderId: '738291461408',
    projectId: 'pollex-18b14',
    storageBucket: 'pollex-18b14.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvjMqdSYYMsoouTrsHoBGeUE0GvIdgJ-Y',
    appId: '1:738291461408:ios:ab82f9f85258e1e2c87b45',
    messagingSenderId: '738291461408',
    projectId: 'pollex-18b14',
    storageBucket: 'pollex-18b14.appspot.com',
    iosClientId: '738291461408-t5cjcteoh0ses3sr4jhp73960fe4kqca.apps.googleusercontent.com',
    iosBundleId: 'com.example.pollex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvjMqdSYYMsoouTrsHoBGeUE0GvIdgJ-Y',
    appId: '1:738291461408:ios:ab82f9f85258e1e2c87b45',
    messagingSenderId: '738291461408',
    projectId: 'pollex-18b14',
    storageBucket: 'pollex-18b14.appspot.com',
    iosClientId: '738291461408-t5cjcteoh0ses3sr4jhp73960fe4kqca.apps.googleusercontent.com',
    iosBundleId: 'com.example.pollex',
  );
}
